adobe/helix-cli

- .eslintignore
- src/build.cmd.js
- test/testBuildCmd.js
> Don't watch in hlx build

- src/deploy.cmd.js
- test/testBlankRemoteDeploy.js
> Generate better action name when no remote can be found

- src/init.cmd.js
- test/testInitCmd.js
> add package-lock.json to generated project

- fixtures/buggy.yaml
- src/strain-config-utils.js
- test/testStrainConfig.js
> Validate strains json

- package.json
- src/up.cmd.js
- src/up.js
- test/testUpCli.js
> Open a browser window on start

- src/up.js
- test/testGeneratedAction.js
- test/testUpCli.js
> [hlx up] should open browser window automatically

- package-lock.json
- package.json
- src/up.cmd.js
> [helix-cli] start-up message

- src/cli.js
- src/deploy-common.js
- test/testCli.js
- test/testDeployCli.js
fixes #64
still not optimal... I start to dislike `yargs` by not doing everything perfect... maybe one day I write my own.... :-)
> cli does not complain about wrong options or commands

- package-lock.json
- test/testDeployCli.js
- test/testStrainCli.js
PR for  #87: I'm saving, discarding and resetting all environment variables starting with `HLX_` before and after each affected test.
> Ensure a clean environment for test cases

- layouts/complete/index.md
- layouts/default/index.md
> Default files should show better instructions

- README.md
- layouts/fastly/helix.vcl
- src/strain.cmd.js
- src/up.cmd.js
- test/fixtures/strains.yaml
> Added an `index` configuration directive for directory indices

- src/cli.js
> [hlx up] exits quietly in a non-git directory 

- layouts/fastly/helix.vcl
> X-Strain is not computed in the /dist case but is needed by hlx_action_root

- src/deploy.cmd.js
> [hlx deploy] print curl request instead of wsk action example 

- package.json
- src/build.cmd.js
- test/testBuildCmd.js
> move 'static' files to ./dist instead of .hlx/dist 

- package-lock.json
- src/strain.cmd.js
- test/fixtures/broken.yaml
- test/testStrainCmd.js
> Check for existence of default strain

- src/deploy.cmd.js
> hlx deploy --no-auto gives error #165

- .circleci/config.yml
Example results here: https://circleci.com/gh/adobe/helix-cli/707
> CircleCI setup for installer

- .circleci/config.yml
- src/build.cmd.js
- src/defaults.js
- src/up.cmd.js
- test/fixtures/alt_webroot.yaml
- test/specs/simple_response.html
- test/testBuildCmd.js
> Implement webroot

- README.md
- layouts/fastly/helix.vcl
- src/strain.cmd.js
> Revert "Edge side implementation of Param whitelist"

- src/build.cmd.js
- test/integration/webroot/dist/vendor/example.css
- test/testBuildCmd.js
- test/utils.js
> hlx build error with bootstrap-grayscale project

- .circleci/config.yml
- build/archive/install.sh
Added an option to overwrite without asking (makes it easier in CI)
> Install overwrite option

- package-lock.json
- package.json
- src/parcel/HelixAsset.js
- bump htlengine and parcel-plugin-htl version
- pass source map along asset types
> #225 Support Source Maps

- src/defaults.js
- test/testBuildCli.js
- test/testUpCli.js
> hlx build does not re-generate the compiled js files #176

- src/clean.cmd.js
- src/clean.js
- src/cli.js
- test/testCleanCli.js
- test/testCleanCmd.js
> Implement hlx clean #26

- src/deploy.cmd.js
> Ugly error message when deploy to openwhisk fails #235

- package-lock.json
- package.json
- src/parcel/OutputTemplate.js
see #196 
see related PR https://github.com/adobe/hypermedia-pipeline/pull/63
> Move all owrequest adapter to pipeline #196

- package-lock.json
- package.json
- src/up.cmd.js
> Use latest petridish which doesn't provide runtime anymore #257

- layouts/fastly/helix.vcl
PR for https://github.com/adobe/helix-cli/issues/240
> [VCL] Compute path properly and use it where needed

- layouts/fastly/helix.vcl
- src/publish.cmd.js
- test/fixtures/api.fastly.com-443/153926815676967910
- test/fixtures/dynamic-version.vcl
- test/testPublishCmd.js
PR for https://github.com/adobe/helix-cli/issues/247
> Use req.vcl to determine the Fastly config version

- src/publish.cmd.js
- test/fixtures/api.fastly.com-443/153926815676967910
- test/fixtures/dynamic-version.vcl
- test/testPublishCmd.js
PR for https://github.com/adobe/helix-cli/issues/266
> Use HTTP Header Subfields for X-Version #266

- layouts/fastly/helix.vcl
PR for https://github.com/adobe/helix-cli/issues/269
> ESI on / are not executed on production #269

- package-lock.json
- package.json
- src/build.js
- src/clean.js
- src/cli.js
- src/demo.js
- src/deploy.cmd.js
- src/deploy.js
- src/log-common.js
- src/perf.js
- src/publish.cmd.js
- src/publish.js
- src/up.cmd.js
- src/up.js
- test/testLogCommon.js
see #248 
needs https://github.com/adobe/helix-shared/pull/3
> Implement `--log-level` #248

- demos/full/helix-config.yaml
- package-lock.json
- package.json
- src/abstract.cmd.js
- src/up.cmd.js
see #303 
- uses latest petridish, hypermedia-pipeline and helix-shared that address the issues metioned in #303
> [hlx up] does not render remote sample content #303

- package-lock.json
- package.json
- src/up.cmd.js
- test/utils.js
https://github.com/adobe/git-server/issues/13
https://github.com/adobe/git-server/issues/38
https://github.com/adobe/git-server/issues/39
https://github.com/adobe/git-server/issues/40
> update petridish@2.5.0 to helix-simulator@2.6.1

- package-lock.json
- src/build.cmd.js
- src/up.cmd.js
- test/testBuildCmd.js
see #313.
- Regression of #295
> Debugging broken in v0.9.0 #313

- .circleci/config.yml
- package-lock.json
- package.json
- src/up.cmd.js
- test/utils.js
> update petridish@2.5.0 to helix-simulator@2.6.1 #317

- layouts/fastly/helix.vcl
- package-lock.json
This is work in progress for #340 
@ejthurgo I'll invite you as a reviewer, so you can leave comments in a consolidated place, not commit by commit.
> Fix Missing Image Optimization

- package-lock.json
- package.json
- src/parcel/OutputTemplate.js
- test/integration/src/xml.js
- test/specs/parcel/async_xml.js
- test/specs/parcel/xml.js
- test/testGeneratedAction.js
> Pure-JS actions are not wrapped #334

- demos/simple/index.md
> fix demos/simple/index.md to show correct location of style.css

- src/publish.cmd.js
> content.path in strain is not updated in edge dictionary #385

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/discussion.md
- .github/ISSUE_TEMPLATE/feature_request.md
Automatically apply tags for issue templates
> Update issue templates

- CONTRIBUTING.md
- README.md
- package.json
> Add npm check command & mention in readmes

- package-lock.json
- package.json
Fixing https://github.com/assaf/node-replay/issues/141
> Upgrade replay

- package-lock.json
- package.json
> Greenkeeper/eslint plugin react 7.12.4

- src/publish.cmd.js
- test/fixtures/no-default-params.vcl
- test/fixtures/no-default-params.yaml
- test/fixtures/some-params.vcl
- test/fixtures/some-params.yaml
- test/testPublishCmd.js
> [regression] params.vcl is not generated correctly #474

- src/up.cmd.js
- src/up.js
- test/fixtures/default-updated-foo.yaml
- test/fixtures/default-updated.yaml
- test/integration/default-config.yaml
- test/specs/simple_response_readme.html
- test/testUpCli.js
- test/testUpCmd.js
> [hlx up] provide an option to simulate a domain with `--host` #108

- src/deploy.cmd.js
- test/fixtures/default-proxy-updated.yaml
- test/fixtures/default-proxy.yaml
- test/fixtures/default-updated-foo.yaml
- test/integration/default-config.yaml
- test/testDeployCmd.js
- test/testUpCmd.js
> hlx deploy does not work when default strains is a proxy strain #488

- demos/full/helix-config.yaml
> Full demo config should include 'local-dev' strain #492

- src/deploy.cmd.js
- test/testDeployCmd.js
> More verbose error message

- layouts/fastly/helix.vcl
- src/fastly/vcl-utils.js
- test/fixtures/proxystrains.vcl
- test/fixtures/urls.vcl
> Incorrect directory path handling #501

- src/package.cmd.js
- src/parcel/RawJSPackager.js
- test/integration/src/utils/another_helper.js
- test/testDeployCmd.js
- test/testPackageCmd.js
- test/testUpCmd.js
> require module in sub-directory produces error while packaging #506

- package-lock.json
- package.json
> Greenkeeper/ajv 6.9.1

- src/deploy.cmd.js
- src/publish.cmd.js
- test/fixtures/default-proxy-updated.yaml
- test/fixtures/default-updated-foo.yaml
- test/fixtures/default-updated.yaml
- test/testDeployCmd.js
> include wsk namespace and use better action names fir dirty deployments.

- src/cli.js
- src/parcel/HelixAsset.js
> hlx build and up failing on windows environment #520

- src/deploy.cmd.js
> static value in proposed strain config always localhost #496

- layouts/fastly/helix.vcl
- package-lock.json
- package.json
- src/fastly/vcl-utils.js
- test/fixtures/default-params.vcl
- test/fixtures/default.vcl
- test/fixtures/proxystrains.vcl
- test/fixtures/simple-condition.vcl
- test/fixtures/urls.vcl
- test/integration/src/html.htl
- test/integration/src/html.pre.js
- test/integration/src/html2.htl
- test/specs/parcel/asynchelpx_html.htl
- test/specs/parcel/helpx_html.htl
- test/testPublishCmd.js
> Harmonize `context.request` and `action.request` #531

- package-lock.json
- package.json
> Greenkeeper/webpack 4.29.3

- package-lock.json
- src/parcel/AdapterJSAsset.js
- test/specs/parcel/require_noext_html.htl
- test/specs/parcel/require_noext_html.pre.js
- test/testGeneratedAction.js
- test/utils.js
> Require without file extension #397

- package-lock.json
- package.json
- src/up.cmd.js
> [hlx up] does not terminate when server errors #542

- test/testDeployCmd.js
> test for missing localhost in output

- package-lock.json
- package.json
- src/deploy.cmd.js
Fixes: https://github.com/adobe/helix-shared/issues/49
> Static: emit events to notify Strains about changes

- demos/full/src/html.htl
- demos/simple/src/html.htl
> Code generated by `hlx demo` is broken #573

- test/testDemoUp.js
- test/utils.js
- Relates to #573 
- Bumps #333
> [TEST] Code generated by `hlx demo` is broken #573

- src/openwhisk/static.js
- test/testStatic.js
fixes #585 might aid https://github.com/adobe/developer.adobe.com/issues/133#issuecomment-466768631
> Force status code 200 for OK responses

- package-lock.json
- package.json
includes https://github.com/adobe/helix-simulator/issues/151
> fix(package): update helix-simulator to 2.10.4

- package.json
- src/git-utils.js
- test/fixtures/gitutils/.gitconfig
- test/fixtures/gitutils/.user_gitignore_global
- test/testGitUtils.js
> hlx deploy reports dirty on non-dirty branch #598

- src/parcel/ExternalsCollector.js
> fix(package): dedupe mods with shorter path

- .npmignore
- src/auth-login-server.js
- src/auth.cmd.js
> fix(auth): Use modified login callback and support variable hosts 

- package-lock.json
- package.json
> Greenkeeper/@adobe/helix pipeline 1.1.1

- package-lock.json
- package.json
> Greenkeeper/chokidar 2.1.5

- test/specs/json_response.json
Adjusted expected `json` output based on new `index.md`
PR for #693
> Master Build is Broken

- package-lock.json
- package.json
- src/up.cmd.js
- test/integration/src/dump_html.htl
- test/integration/src/dump_html.pre.js
- test/specs/dump_response.html
- test/specs/dump_response2.html
- test/testUpCmd.js
> fix(build): invalidate cache of simulator after rebuild

- demos/full/helix-config.yaml
- src/config/default-config.yaml
- test/fixtures/default-proxy-updated.yaml
> new config format in full demo

- src/parcel/packager-config.js
> fix(package): remove extra modules from static.zip (fixes #730)

- test/fixtures/recordings/Dynamic-Strain-VCL-generation_3253923243/initFastly-generates-new-backends-for-defined-Proxies_1740904967/recording.har
- test/fixtures/recordings/Integration-test-for-up-command_3614339512/up-command-delivers-correct-response-_668345128/recording.har
- test/fixtures/recordings/Integration-test-for-up-command_3614339512/up-command-handles-modified-sources-and-delivers-correct-response-_3100915401/recording.har
- test/fixtures/recordings/Static-Delivery-Action-unittest_2612775662/main-returns-static-file-from-GitHub_2955134363/recording.har
- test/fixtures/recordings/Test-VCL-utils_3381835601/initFastly-generates-new-backends-for-defined-Proxies_1740904967/recording.har
- test/testBuildCmd.js
- test/testPublishCmd.js
- test/testStatic.js
- test/testUpCmd.js
- test/testVCLUtils.js
> chore(test): ensure that tests work offline

- package-lock.json
- package.json
- test/specs/api_response_readme.html
- test/specs/simple_response.html
- test/specs/simple_response_readme.html
Includes fixes for https://github.com/adobe/helix-pipeline/issues/26
> Greenkeeper/@adobe/helix pipeline 1.5.0

- package-lock.json
- package.json
> Greenkeeper/postcss 7.0.16

- package-lock.json
- src/git-utils.js
- src/publish.js
- src/remotepublish.cmd.js
- test/fixtures/filtered-master.yaml
- test/fixtures/filtered.yaml
- test/testGitUtils.js
- test/testPublishCli.js
- test/testRemotePublishCmd.filter.js
> Filter strains to publish with --only and --exclude

- package-lock.json
- package.json
> Greenkeeper/snyk 1.163.0

- src/package.cmd.js
> fix(package): use correct log output for debug

- src/hack.cmd.js
- src/hack.js
- test/testHack.js
Incorporated feedback from https://github.com/adobe/helix-cli/commit/7dfe0fc2fcab5411a7c670c39f71416429cf7bdc.
> refactor(hack): add link to next hackathon

- package.json
- src/deploy.cmd.js
- src/deploy.js
- src/package.cmd.js
- src/package.js
- src/remotepublish.cmd.js
- src/static.cmd.js
- src/yargs-static.js
- test/fixtures/recordings/hlx-deploy-Integration-_925098567/Deploy-works_2031710788/recording.har
- test/testDeployCli.js
- test/testDeployCmd.js
- test/testPackageCli.js
- test/testPackageCmd.js
Fixes #850, still WIP. Missing:
This way we can gradually move to binding over building.
> Optionally bind static action instead of building it

- package.json
fixes security issues in sub dependencies
> build(release): update sematic-release to 15.13.12

- src/package.cmd.js
- src/parcel/ExternalsCollector.js
> Package on windows

- package-lock.json
- package.json
- src/package.cmd.js
- test/testPackageCmd.js
> fix(package): dependencies are not correctly bundled

- package.json
> fix(package): add hyperscript as dependency

- package-lock.json
- package.json
> Greenkeeper/snyk 1.171.1

- package-lock.json
- package.json
- src/parcel/OutputTemplate.js
- test/integration/src/html.htl
see https://github.com/adobe/helix-cli/issues/954
> use new pipeline and htlengine for full jsdom support

- docs/concepts.md
- package-lock.json
- package.json
- src/build.cmd.js
- src/parcel/HTLAsset.js
- src/parcel/RuntimeTemplate.js
> refactor(parcel): Assimilate parcel-plugin-htl into cli

- package-lock.json
- package.json
- src/parcel/packager-config.js
This reverts commit 33d64bc393beff6d35a9116227823608522285ae.
> fix(package): revert: add more modules to packager

- src/helix-pages.js
- src/up.cmd.js
- test/fixtures/helix-pages/master/package.json
> fix(pages): install helix-pages dependencies and add to module path

- package-lock.json
- package.json
> Greenkeeper/snyk 1.175.1

- package-lock.json
- package.json
> Greenkeeper/snyk 1.177.0

- package-lock.json
- package.json
- src/parcel/RuntimeTemplate.js
> fix(package): use latest htlengine 3.2.0

- src/deploy.cmd.js
- src/deploy.js
- src/package.cmd.js
- src/package.js
- test/fixtures/all.env
- test/testDeployCli.js
- test/testPackageCli.js
- test/testPackageCmd.js
> feat(package): Make bundle minification configurable

- src/package.cmd.js
fixes error when (re)setting the renderThrottle...
> fix(package): reduce output during package

- src/deploy.cmd.js
- src/deploy.js
- test/fixtures/all.env
- test/testDeployCli.js
- test/testDeployCmd.js
fixes #1007
needs https://github.com/adobe/helix-pipeline/pull/384 to have an effect.
> feat(deploy): Add RESOLVE_GITREF_SERVICE as action param

- src/remotepublish.cmd.js
- test/testRemotePublishCmd.botconfig.js
- test/testRemotePublishCmd.customvcl.js
- test/testRemotePublishCmd.dryrun.js
- test/testRemotePublishCmd.faillogging.js
- test/testRemotePublishCmd.failpurge.js
- test/testRemotePublishCmd.failsecrets.js
- test/testRemotePublishCmd.filter.js
- test/testRemotePublishCmd.js
see https://github.com/adobe/helix-logging/pull/43 which changed the service URL
> fix(publish): use versioned logging service

- src/perf.cmd.js
- test/testPerfCmd.js
see https://github.com/adobe/helix-perf/pull/29 which changed the URL
> fix(perf): use versioned performance service

- package-lock.json
- package.json
> Greenkeeper/@semantic release/GitHub 5.4.2

- src/deploy.cmd.js
> fix(deploy): ensure that static action version is valid

- src/publish.js
- src/remotepublish.cmd.js
- test/testRemotePublishCmd.dispatchVersion.js
> feat(dispatch): allow custom dispatch version

- src/publish.js
- test/testPublishCli.js
> fix(dispatch): dispatchVersion never sent to the publish action

- test/testDeployCmd.js
> fix(tests): use correct polly intercept to avoid warning

- package-lock.json
- package.json
> fix(package): get rid of ExperimentalWarning

- src/deploy.js
- src/package.js
- src/yargs-build.js
- test/testDeployCli.js
- test/testPackageCli.js
> fix(cli): positional file arguments for deploy and publish not respected

- src/auth-login-server.js
- src/auth.cmd.js
- src/cli-util.js
- src/deploy.cmd.js
> Windows fixes

- package-lock.json
- package.json
- test/testDemoCmd.js
> chore(package): update helix-simulator dependency

- src/parcel/OutputTemplate.js
Fixes #1125, test together with https://github.com/adobe/helix-pipeline/tree/uniform-steps
> feat(parcel): support replacing steps in pipeline (#1125)

- src/demo.cmd.js
- test/testDemoCmd.js
Fixes broken tests introduced via PR #1118 
When running `testDemoCmd.js` the following errors show up in the `error.log`:
```
2019-08-20 16:25:13.569 [31merror[39m: encountered unhandled promise rejection at process level: [object Promise], reason: TypeError [ERR_INVALID_ARG_TYPE]: The "promiseFn" argument must be one of type Function or Promise. Received type string
at waitForActual (assert.js:608:11)
at Function.rejects (assert.js:694:31)
at Context.it (/Users/stefan/projects/helix-cli/test/testDemoCmd.js:41:12)
at process._tickCallback (internal/process/next_tick.js:68:7)
2019-08-20 16:25:13.634 [31merror[39m: encountered unhandled promise rejection at process level: [object Promise], reason: AssertionError [ERR_ASSERTION]: Missing expected rejection.
```
#1111, PR #1118 
Thanks …
> Fix test demo cmd

- package.json
> chore: Use renovatebot only once a week

- demos/full/_env
- src/publish.js
- src/remotepublish.cmd.js
- test/testPublishCli.js
- test/testRemotePublishCmd.botconfig.js
> publish: write Github token to Fastly service dictionary

- src/yargs-fastly.js
- src/yargs-openwhisk.js
- test/testDeployCli.js
- test/testPublishCli.js
"fix #1135"
https://github.com/adobe/helix-cli/issues/1135
> fix(publish): hlx publish checks for empty strings

- README.md
- src/publish.js
- src/remotepublish.cmd.js
- test/testPublishCli.js
- test/testRemotePublishCmd.botconfig.js
- test/testRemotePublishCmd.customvcl.js
- test/testRemotePublishCmd.dispatchVersion.js
- test/testRemotePublishCmd.failpurge.js
- test/testRemotePublishCmd.filter.js
- test/testRemotePublishCmd.js
See https://github.com/adobe/helix-home/issues/51
> Introduce Option for Soft and Hard Purges

- src/deploy.cmd.js
> fix(deploy): use major version for helix-static

- package-lock.json
- package.json
Signed-off-by: Ranadeep Polavarapu <ranadeep@icloud.com>
Kind of relates to #973 .
There is a high level security vulnerability thrown by *npm audit*. This fixes this.
> fix(security): high severity vulnerability in deps

- package-lock.json
- package.json
Resolves #973.
Signed-off-by: Ranadeep Polavarapu <ranadeep@icloud.com>
Fixes #973 .
As of installing this package today, the `isomorphic-git` was the only `WARN` thrown by *npm*.
> feat: reduce `WARN`s during `npm install`

- .circleci/config.yml
> Add warning for PR from fork repo

- .circleci/config.yml
PR for https://github.com/adobe/helix-cli/issues/1173
> feat(ci): No smoke tests for PR from forks

- README.md
- test/integration/README.md
Just fixed a few typos in docs.
> fix(docs) : fixed a few typos in markdowns

- package.json
> chore(package.json): include node 12 versions known to work

- package-lock.json
- package.json
> chore(deps): update to @adobe/helix-pipeline 5.6.0

- src/up.cmd.js
- src/up.js
- test/testUpCli.js
- test/testUpCmd.js
> fix(up.cmd): support `hlx up` in local repo checkout without configured origin

- src/up.cmd.js
- src/up.js
- test/integration/default-config-private.yaml
- test/testUpCli.js
- test/testUpCmd.js
> feat(up): automatically add GITHUB_TOKEN to dev params.

- .renovaterc.json
- package.json
> Renovate renovatebot config

- README.md
> document --dev-default

- src/builder/ActionBundler.js
> fix(package): ensure correct module resolution order

- README.md
> docs(readme): remove greenkeeper badge

- package-lock.json
- package.json
- src/abstract.cmd.js
- src/auth.js
- src/build.js
- src/clean.cmd.js
- src/clean.js
- src/demo.cmd.js
- src/demo.js
- src/deploy.js
- src/hack.js
- src/log-common.js
- src/package.cmd.js
- src/package.js
- src/perf.js
- src/publish.js
- src/up.js
- test/testDeployCmd.js
- test/testGeneratedAction.js
- test/testHack.js
- test/testPackageCmd.js
- test/testRemotePublishCmd.botconfig.js
- test/testRemotePublishCmd.customvcl.js
- test/testRemotePublishCmd.dispatchVersion.js
- test/testRemotePublishCmd.filter.js
- test/testRemotePublishCmd.js
- test/testUpCmd.js
- customize helix-log instead of using winston logger provided via helix-shared
todo:
> feat(logging): use helix-log

- src/log-common.js
> fix(cli): use correct parameter to initialize the log level

- src/deploy.cmd.js
- src/package.cmd.js
> fix(log): ensure progress bar uses log correctly

- src/abstract.cmd.js
- src/publish.js
- src/remotepublish.cmd.js
- test/fixtures/helix-index.yaml
- test/testPublishCli.js
- test/testRemotePublishCmd.js
Adds support for https://github.com/adobe/helix-publish/pull/288
> Publish queries

- src/publish.js
> fix(publish): fix parameter passing for publish

- .npmignore
> fix(.npmignore): revert some changes which broke 'hlx demo'

- src/up.cmd.js
> feat(up.cmd.js): watch helix-query.yaml and restart server on modification

- src/publish.js
- src/remotepublish.cmd.js
- test/testRemotePublishCmd.dryrun.js
- test/testRemotePublishCmd.failprepare.js
- test/testRemotePublishCmd.failpurge.js
- test/testRemotePublishCmd.failsecrets.js
- test/testRemotePublishCmd.js
BREAKING CHANGE: This change introduces full support for the new YAML-based conditions language. At the same time, VCL-based conditions (strings) can no longer be used.
fixes #1328
> feat(publish): full condition support with helix-publish@v4

- .vscode/launch.json
- package-lock.json
- package.json
- src/git-utils.js
- test/testGitUtils.js
> feat: port to isomorphic-git v1

- test/fixtures/recordings/Integration-test-for-up-command_3614339512/up-command-delivers-correct-response-_668345128/recording.har
Corresponding fix for https://github.com/adobe/helix-pipeline/issues/662
> fix(embed): fix embed generated link

- README.md
- src/cli.js
- src/deploy.cmd.js
- src/deploy.js
- src/up.cmd.js
- src/up.js
- src/yargs-params.js
- test/fixtures/all.env
- test/integration/defaults.env
- test/integration/defaults.json
- test/testDeployCli.js
- test/testDeployCmd.js
- test/testUpCli.js
- test/testUpCmd.js
> feat(cli): better default parameter parsing

- package-lock.json
- package.json
- src/builder/ActionBundler.js
- src/builder/Builder.js
- src/deploy.cmd.js
- src/package.cmd.js
- test/testDeployCmd.js
> feat(deploy): add project info and dependencies as action annotations

- src/deploy.cmd.js
- test/fixtures/recordings/hlx-deploy-Integration-_925098567/Deploy-works-with-unset-parameters_2567019751/recording.har
- test/testDeployCmd.js
Fix for #1410 by removing all falsy values.
> Deploy empty key fix

- src/builder/ModuleHelper.js
- src/deploy.cmd.js
- src/deploy.js
- test/testDeployCli.js
- test/testDeployCmd.js
> Add timestamp

- src/builder/ModuleHelper.js
- src/package.cmd.js
- src/up.cmd.js
- test/testDeployCmd.js
- test/testPackageCmd.js
- test/testUpCmd.js
- test/utils.js
> feat(up): better support for local directories and --custom-pipeline

- src/abstract.cmd.js
- src/up.cmd.js
> fix(up): reload project on git branch switch

- src/builder/ModuleHelper.js
- test/testUpCmd.js
- test/testUpCmdPages.js
> fix(up): prefer online when installing pipeline

- README.md
- package-lock.json
- package.json
- src/auth.cmd.js
- src/deploy.cmd.js
- src/perf.cmd.js
- src/remotepublish.cmd.js
- test/specs/builder/src/asynchelpx_html.pre.js
- test/specs/builder/src/helpx_html.pre.js
- test/testAuthCmd.js
- test/testPerfCmd.js
- test/testRemotePublishCmd.botconfig.js
> feat(request): request is deprecated; replace with helix-fetch

- src/publish.js
- src/remotepublish.cmd.js
- test/testRemotePublishCmd.dryrun.js
- test/testRemotePublishCmd.failprepare.js
- test/testRemotePublishCmd.failpurge.js
- test/testRemotePublishCmd.failsecrets.js
- test/testRemotePublishCmd.js
BREAKING CHANGE: helix-publish@v6 and helix-dispatch@v4 change the default directory index. Details here: https://github.com/adobe/helix-dispatch/releases/tag/v4.0.0
> feat(publish): use helix-publish@v6

- package-lock.json
- src/deploy.cmd.js
- src/deploy.js
- src/yargs-openwhisk.js
- test/fixtures/recordings/hlx-deploy-Integration-_925098567/Deploy-sets-action-limits_3287876545/recording.har
- test/testDeployCli.js
- test/testDeployCmd.js
> feat: support setting action limits during deploy

- src/deploy.cmd.js
- test/testDeployCmd.js
> fix(deploy): ensure default params win over cli arguments

- src/up.cmd.js
- test/integration-helix-pages/fstab.yaml
- test/specs/pages_response_fstab.html
- test/testUpCmdPages.js
- test/utils.js
> fix(pages): use correct branch for pages project

- src/git-utils.js
> fix(git-utils): avoid potential OOME by iterating sequentially over tags

- package-lock.json
- package.json
- src/git-utils.js
> perf: bump isomorphic-git to 1.8.0, use cache param

- test/integration/src/html.pre.js
see https://github.com/adobe/helix-pipeline/pull/878#issuecomment-724452575
The integration test should now run with the old and the new helix-pipeline
> test(integration): adjust tests to upcoming MDAST changes

- package-lock.json
- package.json
> fix(deps): add AJV 7.x to avoid errors when running pipeline

- test/testAuthCmd.js
> Fix auth test

- src/builder/UniversalTemplate.js
> fix: add data to universal template as well

- test/testUpCmdPages.js
- test/utils.js
updated tests for https://github.com/adobe/helix-simulator/pull/632
> chore(test): fix integration tests for simulator

- src/deploy.cmd.js
- src/deploy.js
- test/testDeployCli.js
> feat(cli): remove unused resolve git ref

- .renovaterc.json
- package-lock.json
- package.json
> fix: upgrade open

- src/server/HelixProject.js
- src/server/HelixServer.js
- src/up.cmd.js
> fix: exception while logging

- package-lock.json
- src/server/utils.js
- test/git-utils.test.js
- test/server.test.js
- test/utils.js
> feat: add CORS and Via headers

- src/server/HelixServer.js
- test/server.test.js
> fix: also add CORS headers for local files

- package-lock.json
- package.json
- src/server/HelixProject.js
- src/server/HelixServer.js
- src/server/Indexer.js
- src/server/utils.js
- src/up.cmd.js
- src/up.js
- test/fixtures/project/helix-query.yaml
- test/server.test.js
- test/up-cli.test.js
> feat: add --print-index to help debug query.yaml

- src/server/HelixImportServer.js
- test/import-cmd.test.js
Some POST request are useful, like for site authentication in order to capture some "protected" content.
> feat: proxy POST requests

- .circleci/config.yml
- package-lock.json
- package.json
- src/up.cmd.js
- test/head-html.test.js
- test/import-cmd.test.js
- test/server-livereload.test.js
- test/server.test.js
- test/up-cmd.test.js
- test/utils.js
fixes #2006
- added support for branches with slash
- added better `nock` handling
- use new codecov uploader (ci)
> fix: branch with slash causes problems

- src/server/utils.js
- test/server.test.js
- test/specs/expected_index_w_lr.html
> feat: inject proxy url as <meta> tag

- src/import.cmd.js
Forgot to switch to `git pull` instead of using `git fetch`. In the current state, commits are downloaded but not locally merged, i.e. no code is updated.
> feat: use pull instead of fetch

- src/server/HelixServer.js
- src/server/utils.js
- test/server-utils.test.js
- test/server.test.js
> fix: propagate query properly

- src/server/HeadHtmlSupport.js
- test/head-html.test.js
> fix: head hashing - support boolean properties

- package-lock.json
- package.json
- src/fetch-utils.js
- src/server/HelixImportServer.js
- test/setup-env.js
> fix: @adobe/helix-fetch -> @adobe/fetch

- package-lock.json
- package.json
- src/server/HeadHtmlSupport.js
- src/server/HelixServer.js
- src/server/utils.js
- test/head-html.test.js
- test/server.test.js
> feat: add support for local dev with authenticated sites

- src/server/utils.js
this is required to make the CLI work within GitHub Codespaces
> fix(proxy): drop proxy-connection header

- src/up.cmd.js
- test/up-cmd.test.js
> feat(up): check branch name length and exit server if it exceeds the maximum

- src/server/HelixImportServer.js
- test/import-cmd.test.js
Fix #2120 
Not sure why I have not added that before but this should address several of my issues!
> feat(import): remove security headers

- src/up.cmd.js
- test/up-cmd.test.js
- test/utils.js
> fix: improve branch check

- src/server/utils.js
- test/server.test.js
> feat: remove content-security-policy header for localhost

- src/server/HelixProject.js
- src/server/HelixServer.js
- src/server/utils.js
- test/fixtures/project/404.html
- test/server.test.js
> feat: serve local 404.html if present

- src/git-utils.js
- test/git-utils.test.js
> Default to main when `hlx up` is used on detached head state

- src/server/HelixImportServer.js
- src/server/utils.js
- test/server-utils.test.js
> fix: improve link rewrite

- README.md
- package-lock.json
- package.json
https://github.com/adobe/helix-cli/issues/2064
> adding aem to CLI in addition to hlx

- .github/ISSUE_TEMPLATE/bug_report.md
https://github.com/adobe/helix-cli/issues/2282
> chore: Update bug_report.md: use aem instead of hlx fix #2282

- src/server/utils.js
- test/server-utils.test.js
> fix(cache): proper root filename handling for subfolders

- src/cli.js
- src/up.js
- test/fixtures/all.env
- test/import-cli.test.js
- test/up-cli.test.js
> fix: ensure that AEM_NO_OPEN works as expected

- .gitignore
- src/server/HelixImportServer.js
- test/import-cmd.test.js
> fix #2354: Resources that redirect to protocol-relative URIs are not handled correctly

- src/up.cmd.js
- test/up-cmd.test.js
> feat(up): support urls with variables

- README.md
> fix(docs): how to migrate from @adobe/helix-cli

- src/server/BaseServer.js
- test/import-server.test.js
- test/server.test.js
> fix(2520): Provide version information about the current aem-cli

- README.md
Fixes https://github.com/adobe/helix-cli/issues/2552
> Minor README update in regards to creating self signed HTTPS certs
