adobe/helix-cli

README.md

Hi @trieloff! I noticed that you wiped out all of the LGTM.com alerts in https://github.com/adobe/helix-cli/pull/35 and enabled automatic code review for pull requests — cool :slightly_smiling_face:! Looking at your list of badges, I thought you might be interested in adding this 'A+' LGTM code quality badge. 
Feel free to ignore/close this PR if you'd rather stick to your current selection of badges!
(Full disclosure: I'm on the team that develops LGTM.com)

Add LGTM.com code quality badge

---

package.json

We've been using a patched version of the OpenWhisk client, but the changes have been released now, so that we can go back to the mainline version.
See apache/incubator-openwhisk-client-js#123

Use released OpenWhisk version

---

demos/full/config.yml
demos/simple/config.yml
src/deploy.cmd.js
src/deploy.js
src/gitutils.js
src/strain.cmd.js
test/fixtures/circleci.com-443/153598406333081578
test/fixtures/circleci.com-443/153598406382587280
test/fixtures/circleci.com-443/153598406382939984
test/fixtures/circleci.com-443/153598406383158374
test/fixtures/circleci.com-443/153598406457647011
test/fixtures/circleci.com-443/153598811993548716
test/fixtures/circleci.com-443/153598811993739328
test/testBlankRemoteDeploy.js
test/testDeployCli.js
test/testDeployCmd.js
test/testGitUtils.js
test/testUpCmd.js

This is a fix for #135 and obsoletes #130. It does no longer have a dependency on #112, as this might take a bit longer to be discussed.
----
The default for `hlx deploy` is `hlx deploy --auto`, which will set up a CI/CD pipeline for the given repository. To do this, we depend on:
(this branch is based on both branches to avoid later merge conflicts)
The rough process will look like this:

Auto-Deployment (without Static Delivery Changes)

---

layouts/fastly/helix.vcl
src/openwhisk/static.js
test/testStatic.js

This is a workaround for the 1 MB response size limit in OpenWhisk:
- if `static.js` detects a file that is bigger than 750k, it will send a `307` redirect to the `raw.githubusercontent.com` location, and set the correct (inferred) `X-Content-Type` header
- when `vcl_fetch` gets a `307` status code from `static.js`, it will restart the request with the URL set in the `Location` header
- when that response is received in `vcl_fetch` again, the `Content-Type` header of the 2nd response will be overwritten with the `X-Content-Type` header from the 1st response

Support for Large Static Binaries

---

package-lock.json
package.json
src/up.cmd.js
test/testUpCmd.js

- use latest petridish v1.4.0
- Code lookup in the wrong repo with 0.7.5 (Fixes #197)

Code lookup in the wrong repo with 0.7.5

---

README.md
layouts/fastly/helix.vcl
src/strain.cmd.js

This is the edge-side implementation for #126: it adds everything on the edge and cli-side to enable passing a parameter `params` that has the names and values of all whitelisted parameters in a URL encoded string. 
On the action-side, you would need to take the value of `params.params` and use `querystring.parse` (https://nodejs.org/api/querystring.html#querystring_querystring_parse_str_sep_eq_options) to get a proper object.
I'm not a 100% sure where you would put that, @kptdobe @tripodsan – therefore only a partial solution to #126

Edge side implementation of Param whitelist

---

src/deploy.cmd.js
src/strain.cmd.js
src/user-agent-util.js
test/testUserAgent.js

This PR standardizes the user-agent used for all requests to
- Fastly
- CircleCI
- GitHub
- OpenWhisk
to something like `@adobe/helix-cli (Project Helix) 0.7.6-pre.0 - darwin 17.7.0`

Standardize User Agent String

---

src/publish.cmd.js
test/fixtures/urls.vcl
test/testPublishCmd.js

see #188
the original test was too weak, as it:
- didn't consider partial matches, i.e. `/helpix/foo/` matches `^/help` which would result in `/somerootix/foo/`
- didn't handle roots with trailing slashes, i.e. `/help` would not match `^/help/`

Setting a "content root" leads to invalid content delivery #188

---

layouts/fastly/helix.vcl

Recently uncovered an issue with the Fastly IO Boilerplate which can
result in reduced CHR when the origin doesn’t pass up caching headers
and we fallback to default TTLs.
Issue would exhibit itself by decreased TTL at the edge resulting in
increased miss-rate to the shield.
Resolves issue: https://github.com/adobe/helix-cli/issues/253

Fixes Reduced CHR when applying default image TTLs

---

demos/full/.circleci/config.yml
demos/simple/.circleci/config.yml
src/perf.js
test/testPerfCli.js

Default CI config cannot be executed ootb #283

---

package-lock.json
package.json
src/up.cmd.js
test/utils.js

Reverts adobe/helix-cli#314
it seems that the tests on circle ci don't like the new git-server:
```
/home/circleci/repo/node_modules/nodegit/dist/nodegit.js:16
throw ex;
^
Error: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory
at Object.Module._extensions..node (module.js:682:18)
```

revert to helix-simulator@2.6.0

---

.circleci/config.yml

auto publish gh release on version tag

---

.circleci/config.yml
build/snykmocha.js
package-lock.json
package.json

See #351 
The [Snyk Runtime](https://snyk.io/docs/runtime-protection) normally expects an express app, so I've been trying to re-create the same kind of monitoring in our unit tests.

Enable Snyk Runtime on CI

---

package-lock.json
src/build.cmd.js
src/defaults.js
src/parcel/AdapterJSAsset.js
src/parcel/HelixAsset.js
src/parcel/OutputTemplate.js
src/parcel/RawJSPackager.js
test/integration/src/helper.js
test/integration/src/xml.js
test/specs/parcel/async_xml.js
test/specs/parcel/xml.js
test/testBuildCmd.js
test/testGeneratedAction.js
test/utils.js

see #334
- adds logic to the parcel bundling that triggers wrapping of all non `.pre.js` assets
the default file filter select all `src/**/*.js` as sources for scripts. we can already filter out the `.pre.js`, but any _helper_ scripts would be difficult to detect.
for example:
```
src
- html.htl
- helper.js
- json.js (requires helper.js)
```
- a. detect if a _helper_ is required by another script, and then reject it as pure-JS script (shaky and might be difficult to implement with current parcel handling)
- b. detect if a script contains a `module.exports.main` and then reject if not (shaky, as a helper also might export a `main`)
- c. only match for known media types: `src/**/*html.js, src/**/*json.js, src/**/*xml.js` etc. might be ok, but is not easy extendable.
- d. only match toplevel …

Pure-JS actions are not wrapped #334

---

src/deploy.cmd.js

Partial fix for #341: no more line breaks in the deploy progress bar, but we should still try to have only one progress bar per action

Better progress bars

---

src/cli.js

This PR enables basic bash completion #202 
You will still need to install the completion script (assuming `hlx` is a global command, not alias)
for `~/.bash_profile`
```bash
_yargs_completions()
{
local cur_word args type_list
cur_word="${COMP_WORDS[COMP_CWORD]}"
args=("${COMP_WORDS[@]}")
type_list=$(hlx --get-yargs-completions "${args[@]}")
COMPREPLY=( $(compgen -W "${type_list}" -- ${cur_word}) )
if [ ${#COMPREPLY[@]} -eq 0 ]; then
COMPREPLY=( $(compgen -f -- "${cur_word}" ) )
fi
return 0
}
complete -F _yargs_completions hlx
```
or for `~/.zshrc`
```bash
_yargs_completions()
{
local reply
local si=$IFS
IFS=$'\n' reply=($(COMP_CWORD="$((CURRENT-1))" COMP_LINE="$BUFFER" COMP_POINT="$CURSOR" hlx --get-yargs-completions "${words[@]}"))
IFS=$si
_describe 'values' reply
}
compdef …
```

Enable bash completion

---

package-lock.json
src/up.cmd.js

Turns out the problem was because I have all of my projects under `~/src/`, i.e. `~/src/Adobe-Developer-Site`, `~/src/helix-cli`, etc. So, the first conditional in this function never was true, so the short-circuit didn't work on my machine.
My approach to fix was to remove the process' current working directory from the absolute path of changed filenames passed into the watcher method.

🐛 fix infinite watch / build loop that only affected me

---

.npmignore

`npm pack` would currently include previously built packages which are still lying around
Relates to #405

add adobe-helix-* to .npmignore

---

src/openwhisk/static.js
test/testStatic.js

Fixes #507 
Fixes https://github.com/adobe/developer.adobe.com/issues/88

OpenWhisk chokes on SVG if not base64 encoded

---

test/fixtures/raw.githubusercontent.com-443/155048558468640026
test/testStatic.js

Relates to #333
This improves test coverage of `/src/openwhisk/static.js` as follows:
```
% Stmts | % Branch |  % Funcs |  % Lines
- 55.71 |    59.26 |    41.67 |    55.71
+ 88.57 |    83.33 |    91.67 |    88.57
```
and overall `helix-cli` test coverage:
```
% Stmts | % Branch |  % Funcs |  % Lines
- 83.24 |    65.85 |    87.21 |    83.15
+ 84.62 |    67.98 |    88.75 |    84.56
```

improve static.js test coverage #333

---

package-lock.json
package.json

Installing the helix-pipeline in the project confuses the execution #513

---

layouts/fastly/helix.vcl

see #591 
also adds action name to trace for better debugging of the request chain.

Fix static 404

---

src/package.cmd.js
src/parcel/ExternalsCollector.js

This is a fix for https://github.com/adobe/helix-pipeline/issues/209 and potentially https://github.com/adobe/developer.adobe.com-planning/issues/183 caused by a version mismatch between ajv 5.x (used by `request`, supporting schema-6) and ajv 6.x (used by `helix-pipeline`, supporting schema-7`.
For `ajv` in particular, we use the global version instead of the version specific to `request`, assuming that the `har-validator` functionality is not used frequently.

Avoid conflicts with module-specific node_modules

---

src/publish.cmd.js
src/publish.js
src/remotepublish.cmd.js
test/testPublishCli.js
test/testPublishCmd.js
test/testRemotePublishCmd.js

(still can be disabled using `--no-remote`) (see #401).
Enable setting the remote publish service URL using `--api-publish` (fixes #647)

Enable remote publishing by default

---

index.js
package-lock.json
package.json
src/config/config-utils.js
test/testCli.js

fix #657
Adds a check to `hlx` for the current node version and reports a warning if version is not supported:
```
$ hlx
Warning: The current node version v8.3.0 does not satisfy
the supported version range >=8.9 <9.0 || >=10.0 < 11.0
You might encounter unexpected errors.
```

feat(cli): check node version and report if not satisfied.

---

src/cli.js
test/testCli.js

Due to the changes for the `.env` file support, the `--log-level` and `--log-file`
arguments didn't work anymore. fixed by defining their camelCase aliases manually.
fixes #756

fix(cli): setting --log-level and --log-file

---

src/publish.js
src/remotepublish.cmd.js
src/yargs-github.js
test/fixtures/all.env
test/fixtures/non-deployed.yaml
test/testPublishCli.js
test/testRemotePublishCmd.botconfig.js
test/testRemotePublishCmd.js

see #793 
Example output:
```
$ hlx publish --update-bot-config
Publishing [==================================================] purged cache 0.0s
Updated the purge-configuration of the following repositories:
- tripodsan/hlxtest#master (api, default)
- tripodsan/hlxtest-content#master (help)
The following repositories are referenced by strains but don't have the helix-bot setup:
- tripodsan/helix-publish#master (stage)
✅  The following strains have been published and version 206 is now online:
- api: https://www.99productrules.com/api
- stage: https://www.99productrules.com/api
- help: https://www.99productrules.com/help
- default: https://www.99productrules.com/
```
The current behaviour is to only update the config, if `--update-bot-config` is set, and it will complain if the …

feat(publish): add --update-bot-config option

---

.circleci/config.yml
package-lock.json
package.json

- create JUnit reports, so that CircleCI can show which tests failed
- run builds in parallel (4 builds, so that wait time isn't too long)
- run eslint in parallel (but not twice)
- use `npm ci` to install pinned dependencies
Fixes #852

Improve our CI

---

README.md
src/build.cmd.js
src/parcel/AdapterJSAsset.js
src/parcel/OutputTemplate.js
src/yargs-build.js
test/integration/src/footer_html.jsx
test/specs/footer_response_readme.html
test/testAdapterJSAsset.js
test/testBuildCli.js
test/testUpCli.js
test/testUpCmd.js

so far only *html.jsx is supported and no examples or tests are included
implements #203
Using the code from here: https://github.com/trieloff/helix-demo/blob/test-branch/src/foo_html.jsx you can create output like this:
```javascript
{ statusCode: 200,
headers:
{ 'Content-Type': 'text/html',
'Cache-Control': 's-maxage=604800',
'Surrogate-Key': 'AYeGDnUcZX/lT0R/omdfQTuQ6J7P9D2fSTpvpzUFacs=' },
body:
'<div class="App"><img class="App-Logo" src="foo.jpg" alt="{title}"><h1 class="App-Title">Helix - demo</h1></div>',
error: undefined }
```

feat(build): add basic JSX support

---

src/parcel/AdapterJSAsset.js

fixes #881
@bdelacretaz does this fix your issue?

fix(parcel): more robust handling of missing package.json

---

src/publish.js
src/remotepublish.cmd.js
test/fixtures/vcl/another.vcl
test/fixtures/vcl/extensions.vcl
test/testPublishCli.js
test/testRemotePublishCmd.customvcl.js
test/testRemotePublishCmd.js

feat(publish): Support for custom VCL logic

---

package-lock.json
package.json
src/parcel/packager-config.js

fixes #966
**Note**: This is not a very satisfying fix. the problem here is really, to determine the minimal set of node modules to run this in production, w/o relying on the dev-dependencies.

fix(package): add more modules to packager

---

src/build.cmd.js
src/build.js
src/up.js
src/yargs-build.js
test/fixtures/all.env
test/testBuildCli.js
test/testBuildCmd.js
test/testDeployCmd.js
test/testPackageCmd.js
test/testUpCli.js
test/testUpCmd.js
test/testUpCmdPages.js
test/utils.js

feat(cli): remove --minify and --cache

---

package.json

Somebody with admin access on github/adobe still needs to install the renovatebot on the repo.
https://github.com/marketplace/renovate

chore: Use renovatebot

---

.circleci/config.yml
package-lock.json
package.json
test/testBuildCmd.js
test/testCleanCmd.js
test/testCli.js
test/testDemoCmd.js
test/testDeployCmd.js
test/testGitUtils.js
test/testJUnitUtils.js
test/testPackageCmd.js
test/testPerfCmd.js
test/testUpCmd.js
test/testUpCmdPages.js

There are more than 16 test failures right now, many seem path-related or otherwise Windows-specific, so I'll need a windows VM to fix them.

Continuous Integration on Windows

---

src/publish.js
src/yargs-fastly.js
test/testPublishCli.js

Rename fastly-namespace to fastly-serviceid, but keep compatibility with old name
"fix #1112"
https://github.com/adobe/helix-cli/issues/1112## Related Issues

refactor(cli): rename fastly-namespace

---

package-lock.json
package.json

`helix-cli` should get internal (@adobe/*) updates sooner than once a week. in fact, it would be good to have them as soon as possible so we can test changes end to end without having to use a manually modified local build.
PS: this will also update `helix-pipeline` to 5.2.0 (latest)

build(dependabot): change update schedule to anytime for @adobe packages

---

test/testPackageCmd.js

see https://circleci.com/gh/adobe/helix-continuous/4916 and https://github.com/adobe/helix-pipeline/pull/453

test(package): relax tests to allow smoke tests to pass with new headers

---

src/publish.js
src/remotepublish.cmd.js
test/testRemotePublishCmd.botconfig.js
test/testRemotePublishCmd.dryrun.js
test/testRemotePublishCmd.failpurge.js

https://github.com/adobe/helix-publish/issues/38

feat(pub): defaults debugKey to serviceid

---

package-lock.json
package.json
test/utils.js

I've been running `npm audit fix` and in 42b5615 I've removed the vulnerable `fstream` dependency (used in testing via `unzip2`, which has been replaced with `yauzl` – Yet another unzip library)

Fix tidelift complaints

---

src/remotepublish.cmd.js
test/testRemotePublishCmd.dryrun.js
test/testRemotePublishCmd.failpurge.js
test/testRemotePublishCmd.js

fixes #1162
**Note**: 
`fastly.writeDictItem()` will remove the edge dictionary entry, if the value is `undefined`.

fix(publish): clear GITHUB_TOKEN from edge dictionary if given

---

src/up.cmd.js
src/up.js
test/testUpCli.js
test/testUpCmd.js

fixes #913
reverts to the original idea:
in `up.js`
- If no `--local-repo` is specified, yargs will default to `.`, since it's the default in the options.
- if only `--local-repo` (with not argument) is specified, yargs will default to `.`, since it's the default in the options. 
- if `--no-local-repo` is specified, yargs will use `false` as value, which is filtered in `coerce`
- any other string is coerced and split accordingly. eg:
```
$ hlx up --local-repo=a,b --local-repo=d,e --local-repo
[ 'a', 'b', 'd', 'e', '.' ]
```
in `up.cmd.js`
- if no local repo is specified, the simulator will automatically use the `cwd`.
- if a local repo has no `.git` directory, an error is thrown. the simulator requires a git repository.
- if a local repo has no origin, the entry is ignored. a warning is …

fix(up): default to --local-repo=.

---

src/publish.js

This is an addendum to #1254 which also changes the default for the CLI, so that the changes become active for most users
see #1254

fix(publish): use correct default version (v3) for publish API

---

README.md
src/yargs-params.js
test/fixtures/all.env
test/testUpCli.js

developers can now provide extra action params that persist dev sessions using $HLX_DEV_DEFAULT env var
"fix #1266"
https://github.com/adobe/helix-cli/issues/1266

feat(cli): dev-defaults can be set with env vars

---

test/fixtures/recordings/Generated-Action-Tests_4194615817/Testing-async_html_1336282281/script-can-be-executed_530277162/recording.har
test/fixtures/recordings/Generated-Action-Tests_4194615817/Testing-asynchelpx_html_1543695720/script-can-be-executed_530277162/recording.har
test/fixtures/recordings/Generated-Action-Tests_4194615817/Testing-helpx_html_56175874/script-can-be-executed_530277162/recording.har
test/fixtures/recordings/Generated-Action-Tests_4194615817/Testing-html_1194330692/script-can-be-executed_530277162/recording.har
test/fixtures/recordings/Generated-Action-Tests_4194615817/Testing-logger_html_1506903279/script-can-be-executed_530277162/recording.har
test/fixtures/recordings/Generated-Action-Tests_4194615817/Testing-promise_html_2549031294/script-can-be-executed_530277162/recording.har
test/fixtures/recordings/Generated-Action-Tests_4194615817/Testing-require_html_3192821112/script-can-be-executed_530277162/recording.har
test/fixtures/recordings/Generated-Action-Tests_4194615817/Testing-require_noext_html_2725768335/script-can-be-executed_530277162/recording.har
test/fixtures/recordings/Generated-Action-Tests_4194615817/Testing-return_async_html_40026840/script-can-be-executed_530277162/recording.har
test/fixtures/recordings/Generated-Action-Tests_4194615817/Testing-return_promise_html_1087596227/script-can-be-executed_530277162/recording.har
test/fixtures/recordings/Generated-Action-Tests_4194615817/Testing-return_simple_html_3798695710/script-can-be-executed_530277162/recording.har
test/fixtures/recordings/Generated-Action-Tests_4194615817/Testing-simple_html_1612831361/script-can-be-executed_530277162/recording.har
test/fixtures/recordings/Integration-test-for-up-command_3614339512/up-command-delivers-correct-response-from-private-repo-_1570021791/recording.har

PR for #1353 
The tests are still failing but the failure is only now due to error covered by https://github.com/adobe/helix-pipeline/pull/644.

chore(test): record requests to helix-markup.yaml

---

test/specs/json_response.json

With the new pipeline changing how we order the meta types for better consistency, we need to update the cli's up command tests to match the new order
fix adobe/helix-pipeline#issues/669

test(up-cmd): adjust tests for new helix pipeline version

---

package-lock.json
package.json
src/build.cmd.js
src/builder/Builder.js
src/up.cmd.js
src/up.js
test/fixtures/all.env
test/fixtures/recordings/Integration-test-for-up-command_3614339512/up-command-delivers-correct-response-_668345128/recording.har
test/fixtures/recordings/Integration-test-for-up-command_3614339512/up-command-delivers-correct-response-with-live-reload-_1789795472/recording.har
test/specs/simple_response_with_livereload.html
test/testUpCli.js
test/testUpCmd.js
test/testUpCmdPages.js

- adds a new flag `--livereload` which is `true` by default
- when enabled, instructs the helix-simulator to enable live-reload. it will inject the live-reload javascript to the html reponses. the script establishes a web-socket connection with the dev-server and the server will send events to the clients when a file was modified.
see https://github.com/adobe/helix-simulator/issues/445

feat(up): add support for live-reload

---

docs/concepts.md
src/deploy.cmd.js
src/package.cmd.js
test/testDeployCmd.js

removing `hlx--static` action because dispatch now used `helix-services/static@v1`
see https://github.com/adobe/helix-dispatch/issues/319

fix(deploy): remove unused hlx--static

---

.circleci/config.yml
package-lock.json
package.json
src/auth.cmd.js
src/deploy.cmd.js
src/perf.cmd.js
src/remotepublish.cmd.js
test/specs/builder/src/asynchelpx_html.pre.js
test/specs/builder/src/helpx_html.pre.js
test/testAuthCmd.js
test/testRemotePublishCmd.js

feat(deps): upgrade to helix-fetch v2

---

src/builder/ActionTemplate.js

Allows the `data` property in `content` to stay alive between individual pipeline steps, relates to https://github.com/adobe/helix-pipeline/pull/992

fix: keep data property in content

---

test/fixtures/recordings/Integration-test-for-up-command_3614339512/up-command-delivers-correct-response-_668345128/recording.har
test/fixtures/recordings/Integration-test-for-up-command_3614339512/up-command-delivers-correct-response-with-live-reload-_1789795472/recording.har
test/fixtures/recordings/Integration-test-for-up-command_3614339512/up-command-handles-modified-sources-and-delivers-correct-response-_3100915401/recording.har
test/specs/simple_response.html
test/specs/simple_response_with_livereload.html

adobe/helix-pipeline#1056 switches the embed service URL to universal runtime. This means that some of the recordings for the integration tests need to be re-downloaded, as the URL has changed. As helix-embed has evolved in the meantime, this also means that the test output has changed a bit. There is a good chance that we will end up in a smoke test deadlock, as this PR won't pass the tests until adobe/helix-pipeline#1056 has been merged and vice versa.

test(integration): fix test recordings for embeds on universal runtime

---

src/up.cmd.js
test/testUpCmd.js

fix(cli): add error message for hlx up command in submodule repo

---

src/server/HelixProject.js
src/server/HelixServer.js
src/up.cmd.js
src/up.js
test/server-utils.test.js
test/server.test.js
test/specs/expected_goodbye.txt
test/up-cli.test.js

- feat(server): add `/.kill` switch to quickly turn the server off
- feat(cli): add `--kill` option (default: on) to kill other Helix CLI server instances on the same port
fixes #1939

Implement kill switch

---

.circleci/config.yml
src/server/utils.js
test/server-utils.test.js

Follow up from #1956 which has not been released because of failing Windows tests.
@trieloff @tripodsan any specific reason why `build_win` is currently commented out in the CircleCI config ? I would have seen the problem before merging into main...

chore: fix and enable Windows tests 

---

src/server/utils.js
test/server-utils.test.js

If the query string is long (graphql...), the filename becomes too long and file cannot be saved on disk. Use md5 hash of the qs to still be able to store the file.

fix: hash qs if too long

---

src/server/HelixServer.js
src/up.js
test/server.test.js
test/up-cli.test.js

While working on code coverage for the import proxy, I realised that one line on the `kill` feature is not covered by a test. And when the test is written, you see that the implementation is not correct.

fix: fix kill implementation

---

src/server/HelixImportServer.js
test/import-cmd.test.js

The 301 support got lost while implementing the `hlx import` command. Re-adding it.

feat: import - support 301

---

src/server/HelixImportServer.js
test/import-cmd.test.js

If the remote host sets a cookie, the `hlx-proxyhost` cookie used to proxy page resources is lost.
Just get rid of the remote host cookie and force the `hlx-proxyhost` in all responses.

fix: hlx-proxyhost cookie gets lost if remote server has a cookie

---

src/server/HelixImportServer.js

fix typo in `HelixImportServer.js`
```
res.status(404).send(`Unknown path: ${ctx.path}`);
```

fix: typo in proxy mode route handler

---

src/import.cmd.js
src/import.js
test/import-cli.test.js
test/import-cmd.test.js

Fix #2031 
The importer-ui project build process is really slow (more than one minute), I will look at that separately. 
Another approach could also be to package the importer UI together with the hlx cli...
I also did not implement the git fetch + build if the project is already there mainly because the build process is super slow. Impact is that `hlx import` would always be slow to start.

feat: install and build importer-ui

---

src/server/HelixImportServer.js

When trying to use the importer with https://personal.nedbank.co.za/borrow/personal-loans.html, you get error:
```
unable to verify the first certificate
```
The certificate check should be removed in the proxy requests.

feat: disable certificate check

---

package-lock.json
package.json
src/server/HelixServer.js

Adds compression to helix up removing Chrome dev tools recommendations to compress when developing locally. Fixes #2087.
On by default so no switches required.
Unfortunately the package-lock file was created with an old version of npm, so that got patched also.

Added compression, tested locally 

---

src/up.cmd.js
test/up-cmd.test.js
test/utils.js

see https://cq-dev.slack.com/archives/C9KD0TT6G/p1670339689943809
This is the restarting code only (which does not actually restart, just change the proxy URL behind the scenes). Tests weren't as involved as I expected.

update proxy url when get head or remotes change

---

src/server/utils.js
test/server-livereload.test.js
test/specs/expected_index_w_lr_nohead_codespaces.html

this will tweak the livereload to pull the events from another host, as GH Codespaces creates one host per forwarded port.

feat(livereload): add compatibility with codespaces

---

README.md
package.json
src/cli.js
src/hack.cmd.js
src/import.cmd.js
src/import.js
src/server/BaseServer.js
src/server/HelixImportProject.js
src/server/HelixImportServer.js
src/server/HelixProject.js
src/server/HelixServer.js
src/server/Indexer.js
src/server/LiveReload.js
src/up.cmd.js
src/up.js
test/cli.test.js
test/fixtures/all.env
test/git-utils.test.js
test/server-livereload.test.js
test/utils.js

BREAKING CHANGE: hlx up and the HLX_ env prefix no longer work. use aem and AEM_ instead.
fixes #2248 
fixes #2093

fix: more AEM branding

---

index.js
src/config/config-utils.js
test/cli.test.js

shows a deprecation warning and exiits:

fix: show deprecation warning and exit

---

src/abstract-server.cmd.js
test/abstract-server-cmd.test.js

fix: reject dangerous url characters (--open)

---

src/server/HeadHtmlSupport.js
src/server/HelixProject.js
src/server/utils.js
src/up.cmd.js
test/head-html.test.js
test/server.test.js
test/up-cmd.test.js

This fix changes the way how the remote head.html is loaded (the remote head.html version is needed to properly calculating how the local head.html needs to be injected into the html page).
instead of fetching the head.html during startup, it is deferred until the proxy server actually needs it. this is after the browser sent eventual request cookie. this allows that the remote head.html can be fetched also for authenticated sites.
fixes #2274

fix: defer loading of head.html to allow inclusion of request cookie

---

src/server/HelixServer.js
src/server/RequestContext.js
src/server/utils.js

fix: don't respond when headers already sent

---

src/abstract-server.cmd.js
src/fetch-utils.js
src/import.cmd.js
src/import.js
src/server/BaseServer.js
src/server/HeadHtmlSupport.js
src/server/HelixImportProject.js
src/server/HelixImportServer.js
src/server/HelixProject.js
src/server/utils.js
src/up.cmd.js
src/up.js
test/import-cli.test.js
test/up-cli.test.js

fix: support allow-unauthorized in aem up

---

src/up.cmd.js

https://github.com/adobe/helix-cli/issues/2369
Provide a better error in case the `gitUrl` is not found due to not having configured a remote 'origin', rather than a JS error without any hints on what went wrong.

Fix: improve aem up error handling

---

README.md
src/up.cmd.js

The `unable to get local issuer certificate` error has been stumping our customers for a while now
and it typically takes some time to route the issue to me, who can point to the nodejs docs, customer's
IT department, and firewall. By intercepting the error code I hope that we can point people into the
right direction a bit faster.

feat(security): provide more troubleshooting instructions on `aem up`

---

src/up.cmd.js

#2248
Fixing an error message I encountered, that mentioned the deprecated `hlx` command name

fix: update command name in message from 'hlx' to 'aem'

---

src/git-utils.js
src/import.cmd.js
src/import.js
test/import-cmd.test.js
test/utils.js

Extend the `--ui-repo` parameter to allow a branch specifier, which will make socializing new feature branches easier:
`aem import -ui-repo=https://github.com/adobe/helix-importer-ui#<by-branch>`
#2426 
@kptdobe I realize you didn't really support this idea, but I went ahead to see the effort involved.
cc @arumsey @catalan-adobe @karlpauls 
Missing from this is an indicator on the UI of the branch, other than 'main', that is being used.  I tried a few ways but thought I would submit this PR without it.  Output from `aem import` is explicit about the branch.

#2426 Allow import branch specification

---

README.md

- include `aem import` in the README and link to `helix-importer-ui`

docs: Add aem import to README

---

src/server/HeadHtmlSupport.js
src/server/HelixProject.js
src/server/HelixServer.js
src/server/utils.js
src/up.cmd.js
src/up.js
test/fixtures/all.env
test/head-html.test.js
test/up-cli.test.js
test/up-cmd.test.js

Enables passing of  `--site-token secre-token` to `aem up`

feat: Allow passing site token for hlx5 authenticated sites

---

src/up.cmd.js
test/server.test.js
test/up-cmd.test.js

Some IDP configurations do not support the option of prompting to skip login and for these the CLI login fails, as state information is not carried between retries.
In order to fix this, we use `selectAccount=true` from the beginning for Helix CLI logins.

fix: Force Selecting Account when logging in via the CLI

---

package.json
src/server/HelixImportServer.js
test/import-server.test.js

One of our customer sites was optionally using zstd, which is not supported and was causing a blob to be returned as the body instead of the actual html.

Remove accept-encoding in proxy call to use nodejs defaults

---

src/log-common.js

**SUMMARY**
This PR updates logger creation from `Map` to plain objects to work with `@adobe/helix-log@7.0.0`
Since [@adobe/aem-cli@16.10.40](https://github.com/adobe/helix-cli/releases/tag/v16.10.40), which updated `helix-log` to `7.0.0`, no logs appear in the terminal when running `aem up`. Dev server runs silently without outputting anything to console.
When [this line](https://github.com/adobe/helix-log/blob/main/src/log.js#L667) changed from `dict(loggers)` to `Object.entries(loggers)`, it impacted `Map` support which is what `aem-cli` was using to create loggers. 
**TESTING**
- Tested on multiple projects with `node v24.6.0`

fix: make logger compatible with helix-log v7.0.0

---

src/import.cmd.js
src/import.js
src/server/HelixImportProject.js
src/server/HelixImportServer.js
test/dump-headers.test.js
test/import-cli.test.js

fixes: #2576 
Sample output:
```
info: =======================
info: === REQUEST HEADERS ===
info: Request URL: https://www.adobe.com/icon.svg
info: Request Method: GET
info: pragma: no-cache
info: cache-control: no-cache
info: sec-ch-ua-full-version-list: "Not;A=Brand";v="99.0.0.0", "Google Chrome";v="139.0.7258.139", "Chromium";v="139.0.7258.139"
info: sec-ch-ua-platform: "macOS"
info: sec-ch-ua: "Not;A=Brand";v="99", "Google Chrome";v="139", "Chromium";v="139"
info: sec-ch-ua-bitness: "64"
info: sec-ch-ua-model: ""
info: sec-ch-ua-mobile: ?0
info: sec-ch-ua-arch: "arm"
info: sec-ch-ua-full-version: "139.0.7258.139"
info: user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/139.0.0.0 Safari/537.36
info: dnt: 1
info: …
```

fix(2576): provide a way to dump all headers

---

src/server/HelixProject.js
src/server/HelixServer.js
src/server/utils.js
src/up.cmd.js
src/up.js
test/server.test.js
test/up-cli.test.js

Support passing all cookies while proxying, in both directions, e.g. for custom authentication.
_**Update after I created the PR:** Originally I was trying to run `aem up` aka `localhost:3000` as proxy before a custom cloudflare worker where we do authentication using cookies. To make that authentication work, `aem up` needs to proxy cookies in both directions, which is what this PR enabled._
_But in the meantime I figured it's better to simulate the real setup where the cloudflare worker runs in front of Helix. Hence I am running the cloudflare worker (`wrangler dev`) locally now _in front_ of EDS, using `localhost:3000` as origin for Helix requests, so it can talk to `aem up` running locally as well. See https://github.com/aemsites/koassets/pull/32. For that I don't need this PR._
1. …

fix(up): proxy all cookie and set-cookie headers
